config/routes.rb
Rails.application.routes.draw do
  root 'weather#home'
  get '/another_day', to: 'weather#forecast'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/weather_controller.rb
class WeatherController < ApplicationController
  def home

  end

  def forecast
    @city = params[:city]
    @day  = params[:day].to_i
    @cities = ["Bishkek", "Talas", "Batken"]
    @days = [1, 2, 3, 4, 5]
    @apixu_forecast = WeatherGemKg::Generator.new("#{@city}", @day,
      WeatherGemKg::Clients::Apixu.new).generate_me
    @dark_forecast  = WeatherGemKg::Generator.new("#{@city}", @day,
      WeatherGemKg::Clients::DarkSky.new).generate_me
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/weather_helper.rb
module WeatherHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>KgWeather</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: "layouts/front/header" %>
    <%= yield %>
  </body>
</html>

app/views/layouts/front/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to "WeatherKG", root_path, class: "navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to "Forecast for 1 day", another_day_path(city: "Bishkek", day: 1) %> |
        <%= link_to "Forecast for another days", another_day_path(city: "Bishkek", day: 5) %>
      </li>
    </ul>
  </div>
</nav>

app/views/weather/_another_day.html.erb
<div class="apixu">
  <h4>Apixu</h4>
  <div class="row another_day">
    <% @apixu_forecast.each do |day| %>
      <div class="col-md-2">
        <b><%= day[:date] %></b><br>
        day +<%= day[:max_temp] %><br>
        night +<%= day[:min_temp] %><br>
        <%= day[:condition] %><br>
      </div>
    <% end %>
  </div>
</div>

<div class="dark_sky" style="margin-top: 30px;">
  <h4>Dark Sky</h4>
  <div class="row another_day">
    <% @dark_forecast.each do |day| %>
      <div class="col-md-2">
        <b><%= day[:date] %></b><br>
        +<%= day[:max_temp] %><br>
        +<%= day[:min_temp] %><br>
        <%= day[:condition] %><br>
      </div>
    <% end %>
  </div>
</div>

app/views/weather/_five_day.html.erb
<div class="apixu">
  <h4>Apixu</h4>
  <div class="row five_day">
    <% @apixu_forecast.each do |day| %>
      <div class="col-md-2">
        <b><%= day[:date] %></b><br>
        day +<%= day[:max_temp] %><br>
        night +<%= day[:min_temp] %><br>
        <%= day[:condition] %><br>
      </div>
    <% end %>
  </div>
</div>

<div class="dark_sky" style="margin-top: 30px;">
  <h4>Dark Sky</h4>
  <div class="row five_day">
    <% @dark_forecast.each do |day| %>
      <div class="col-md-2">
        <b><%= day[:date] %></b><br>
        +<%= day[:max_temp] %><br>
        +<%= day[:min_temp] %><br>
        <%= day[:condition] %><br>
      </div>
    <% end %>
  </div>
</div>

app/views/weather/_one_day.html.erb
<div class="row">
  <div class="col-md-6">
    <h4>Apixu</h4>
    <div class="one_day">
      <% @apixu_forecast.each do |day| %>
          <h4><%= @city %></h4>
          <%= day[:date] %> |
          <p class="float-right"><%= day[:condition] %></p><br>
          day +<%= day[:max_temp] %><br>
          night +<%= day[:min_temp] %><br>
      <% end %>
    </div>
  </div>
  <div class="col-md-6">
    <h4>Dark Sky</h4>
    <div class="one_day">
      <% @dark_forecast.each do |day| %>
          <h4><%= @city %></h4>
          <%= day[:date] %> |
          <p class="float-right"><%= day[:condition] %></p><br>
          day +<%= day[:max_temp] %><br>
          night +<%= day[:min_temp] %><br>
      <% end %>
    </div>
  </div>
</div>

app/views/weather/forecast.html.erb
<div class="main_cont container">
  <% if @day >= 2 %>
    <span style="font-size: 30px">Forecast for <%= pluralize(5, 'day') %> - <%= @city %></span>
  <% else %>
    <span style="font-size: 30px">Forecast for 1 day</span>
  <% end %>
  <span class="float-right">
    Choose the city
    <%= select_tag 'city',options_for_select(@cities.collect{ |u| u }), id: 'city' %>
    <% if @day >= 2 %>
      <%= select_tag 'day',options_for_select(@days.collect{ |u| u }), id: 'day' %>
    <% end %>
    <button type="button" id="show" class="btn btn-sm btn-primary">Show</button>
  </span>
  <% if @day >= 2 %>
      <%= render partial: "another_day" %>
  <% elsif @day == 1 %>
    <%= render partial: "one_day" %>
  <% end %>
</div>

app/views/weather/home.html.erb
<div class="container main_cont">
  <h1 align='center'>Forecast for Kyrgyzstan</h1>
  <div class="row" align='center'>
    <div class="col-md-6">
      <%= link_to "Forecast for 1 day", another_day_path(city: "Bishkek", day: 1),
        class: 'btn btn-primary' %>
    </div>
    <div class="col-md-6">
      <%= link_to "Forecast for another days", another_day_path(city: "Bishkek", day: 5),
        class: 'btn btn-primary' %>
    </div>
  </div>
</div>